### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by ErnestoNCarrea** [johnhearfield/flarum-ext-oauth-google#2]
Hi, I'm having trouble using this extension.

The extension seems to be configured OK, but when I try to login, after I enter my Google username and password, I get a 301 HTTP error with this address:

https://urlofmysite.com/auth/google?state=(blahblah)&code=(blahblah)#

I'm using the .htaccess file provided by Flarum. It's a 64-bit CentOS 7, with Apache 2.4.16 and PHP 7. Everything else works as expected and the error log is empty. I'm reporting this because I can't find an external cause for this problem.

Thanks in advance.

**Comment by johnhearfield** [comment]
Im slightly confused by your question.
In the title you say 403 and in the description you say 301.

It may be that you have misconfigured something incorrectly, not too sure.

OS and package versions shouldn't really affect anything. The only thing that stands out is PHP7, but that shouldn't really be an issue as it hasn't changed anything fundamentally.

The plugin uses the '[league/oauth2-google](https://github.com/thephpleague/oauth2-google)' package, and uses the .5 beta version of Flarum. I haven't checked any versions later than that, so it might be it's deprecated after.

What version of Flarum are you using, since I haven't been able to keep up to date with the development recently?

I'll have a look at the weekend to see if I can resolve the problem, it might just be you havent configured on the Google side, I'm not too sure.

**Comment by ErnestoNCarrea** [comment]
Hi, thanks for your reply.

The error code is 403 Forbidden, my mistake.

I'm using Flarum beta 5, which is the latest version. The google side seems to be OK, since I got to enter my email, my password and then I get to briefly see a Google redirect and then another redirect to https://urlofmysite.com/auth/google?state=(blahblah)&code=(blahblah)# which gives the 403.

I think it's either the route /auth/google is not recognized by Flarum or it's recongnized but the OAuth extension is returning an access denied error or something like that. But I can't find any useful log.

Tomorrow I will try a new install and see if the problem shows.

**Comment by ErnestoNCarrea** [comment]
Confirmed, the problem persists on a fresh Flarum install. The integrated Facebook and Twitter extensions work without a problem.

**Comment by johnhearfield** [comment]
Have you tried setting the hd param domain? This would require a Google Apps account (paid, but free trail for 14 days or something) just to test. If not I'll have a look later on a local install without the hd param, and go through the steps again.

Sorry about this.

**Comment by alexgrozav** [comment]
Hi @johnhearfield, I'm getting the same error. Google side passes ok, but when the callback returns to the website I get a 403 Forbidden error.

```
http://support.pixevil.com/auth/google?state=...&code=...
```

**Comment by johnhearfield** [comment]
Could you comment out the hd paean in the code and try that way? I haven't had time for to dig deeper into the issue due to work constraints. I'll try and have a look as soon as

Many thanks,
John

**Comment by stevedotmt** [comment]
I fixed this issue by enabling the GooglePlus API inside of the developer console. More information here in this thread https://discuss.flarum.org/d/3117-google-oauth-plugin/22. Should we upload the documentation in the README? I wouldn't mind doing a PR

**Comment by johnhearfield** [comment]
@SteveAzz It's always the simple things people oversee that make it not work, haha. If you wouldnt mind doing a PR with the documentation, that'd be great, cheers. Really should of added that at the beginning to clear up much confusion. 

My apologies.

**Comment by stevedotmt** [comment]
Will be done within a week, no worries you saved me a ton of work by OSS the extension thank you very much!

**Comment by johnhearfield** [comment]
No worries, I'll add a small footnote until the documentation is done
